#!/bin/bash

set -e

type curl >/dev/null 2>&1 || { echo >&2 "Package curl not installed. Run 'apt-get install curl' and try again. Aborting."; exit 1; }

DART_BUILD=${1:-"latest"}
DART_SDK_URL="http://storage.googleapis.com/dart-archive/channels/stable/release/$DART_BUILD/sdk/dartsdk-linux-x64-release.zip"
CDIR=$(pwd)
WDIR=$(mktemp -d /tmp/patch-dartsdk-linux.XXXXXXXX)
DART_SDK_DIR=$WDIR/dart-sdk
DART_SDK_BIN=$DART_SDK_DIR/bin
DART_SDK_LIB=$DART_SDK_BIN/lib

# http://packages.ubuntu.com/precise/libc6
# http://packages.ubuntu.com/precise/libgcc1
# http://packages.ubuntu.com/precise/libstdc++6

URLS="\
http://archive.ubuntu.com/ubuntu/pool/main/e/eglibc/libc6_2.15-0ubuntu10.18_amd64.deb \
http://archive.ubuntu.com/ubuntu/pool/main/g/gcc-4.6/libgcc1_4.6.3-1ubuntu5_amd64.deb \
http://archive.ubuntu.com/ubuntu/pool/main/g/gcc-4.6/libstdc++6_4.6.3-1ubuntu5_amd64.deb \
"

LIBS="\
lib/x86_64-linux-gnu/ld-2.15.so \
lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 \
lib/x86_64-linux-gnu/libc-2.15.so \
lib/x86_64-linux-gnu/libc.so.6 \
lib/x86_64-linux-gnu/libdl-2.15.so \
lib/x86_64-linux-gnu/libdl.so.2 \
lib/x86_64-linux-gnu/libgcc_s.so.1 \
lib/x86_64-linux-gnu/libm-2.15.so \
lib/x86_64-linux-gnu/libm.so.6 \
lib/x86_64-linux-gnu/libpthread-2.15.so \
lib/x86_64-linux-gnu/libpthread.so.0 \
lib/x86_64-linux-gnu/librt-2.15.so \
lib/x86_64-linux-gnu/librt.so.1 \
usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.16 \
usr/lib/x86_64-linux-gnu/libstdc++.so.6 \
"

cd $WDIR

# Download and extract Dart SDK
echo "Downloading $DART_SDK_URL"
curl -s -O -L $DART_SDK_URL
echo "Extracting $(basename $DART_SDK_URL)"
unzip $(basename $DART_SDK_URL)
mkdir -p $DART_SDK_LIB
echo

# Download and extract Ubuntu packages
for url in $URLS ; do
  echo "Downloading $url"
  curl -s -L -O $url
  echo "Extracting $(basename $url) to $WDIR"
  ar p $(basename $url) data.tar.gz | tar zx
  echo
done

# Copy library from Ubuntu packages to Dart SDK
for lib in $LIBS ; do
  echo "Copying $lib"
  cp -a $lib $DART_SDK_LIB
  chmod +x $DART_SDK_LIB/$(basename $lib)
done

# Replace dart executable
echo "Patching Dart SDK"
mv $DART_SDK_BIN/dart $DART_SDK_BIN/dart.bin
cat << EOF > $DART_SDK_BIN/dart
#!/bin/bash
PWD=\$(dirname \$0)
\$PWD/lib/ld-linux-x86-64.so.2 --library-path \$PWD/lib \$PWD/dart.bin \$* &
PID="\$!"
trap "kill \$PID" SIGTERM SIGINT
wait %1
exit \$?
EOF
chmod -R a+rX $DART_SDK_DIR
chmod +x $DART_SDK_BIN/dart
echo

# Tarball patched SDK
echo "Tarball patched SDK"
rm -f $(basename $DART_SDK_URL)
zip -r $CDIR/$(basename $DART_SDK_URL) dart-sdk

# Cleaning
rm -rf $WDIR
